export const ADD_PRODUCT = " ADD_PRODUCT";
export const ALL_PRODUCT = "ALL_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SALE_PRODUCTS ="SALE_PRODUCTS";
export const FOUND_PRODUCTS = "FOUND_PRODUCTS";
export const ADD_SALE = "ADD_SALE";
export const NEW_AMOUNT = "NEW_AMOUNT";
export const ALL_SALE = "ALL_SALE";
export const USER = "USER";